### ISSUE TITLE
Do not use the all Google Play services SDK

### ISSUE THREAD

**Issue by kherembourg** [EulerianTechnologies/eanalytics-android#1]
In your sdk you're using the Google Play Services SDK to get the advertising id.
But you're using an old version (6.5) and the complete SDK which increase greatly the number of methods in our application. More than 15 000 methods are added when the limit is 65 000.
Could you use just a portion of the Google Play Services ? Like analytics for example (works for sure) : 
```java
com.google.android.gms:play-services-analytics:9.2.0
```
It's even possible that the base sdk is enough for what you need (to be tested) : 
```java
com.google.android.gms:play-services-base:9.2.0
```

For more information : 

> https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project

On my application I integrated your SDK but I also excluded the Google Play Services SDK because I already have everything needed with my integration of Google Analytics : 
```groovy
compile('com.eulerian.android.sdk:eanalytics:1.6.1') {
        exclude group: 'com.google.android.gms'
    }
```
I think you should also inform your customers about that in your README.

**Comment by matjmat** [comment]
Bonjour Kevin,
  merci pour votre retour, nous regardons et revenons vers vous dès que 
possible.

Mathieu

Le 06/07/2016 15:40, Kevin Herembourg a écrit :
> In your sdk you're using the Google Play Services SDK to get the
> advertising id.
> But you're using an old version (6.5) and the complete SDK which
> increase greatly the number of methods in our application. More than 15
> 000 methods are added when the limit is 65 000.
> Could you use just a portion of the Google Play Services ? Like
> analytics for example (works for sure) :
>
> com.google.android.gms:play-services-analytics:9.2.0
>
> It's even possible that the base sdk is enough for what you need (to be
> tested) :
>
> com.google.android.gms:play-services-base:9.2.0
>
> For more information :
>
>     https://developers.google.com/android/guides/setup#add_google_play_services_to_your_project
>
> On my application I integrated your SDK but I also excluded the Google
> Play Services SDK because I already have everything needed with my
> integration of Google Analytics :
>
> compile('com.eulerian.android.sdk:eanalytics:1.6.1') {
>          excludegroup:'com.google.android.gms'
>      }
>
> I think you should also inform your customers about that in your README.
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/EulerianTechnologies/eanalytics-android/issues/1>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AJvwX7NsQOBfnHhfXr5tE6lIXS3zzasFks5qS7BpgaJpZM4JGFt2>.
>


-- 
Mathieu JONDET, co-founder & CPO	Cell:	+ 33 6 20581277	
Eulerian Technologies SAS       	52bis rue ramponeau
75020 Paris - FRANCE         		http://www.eulerian.com
